# System level config
SATELLITE_R = 25 * 1000
NUMBER_UE = 5
NUMBER_SATELLITES = 2
SATELLITE_V = 7.56 * 1000
SATELLITE_GROUND_DELAY = 30
SATELLITE_SATELLITE_DELAY = 10
DURATION = 500

# Parameters

MEASUREMENT_REPORT = "MEASUREMENT_REPORT"
HANDOVER_REQUEST = "HANDOVER_REQUEST"
HANDOVER_ACKNOWLEDGE = "HANDOVER_ACKNOWLEDGE"
RRC_RECONFIGURATION = "RRC_RECONFIGURATION"
RRC_RECONFIGURATION_COMPLETE = "RRC_RECONFIGURATION_COMPLETE"
RRC_RECONFIGURATION_COMPLETE_RESPONSE = "RRC_RECONFIGURATION_COMPLETE_RESPONSE"

PROCESSING_TIME = {
    MEASUREMENT_REPORT: 0.5,
    HANDOVER_REQUEST: 0.5,
    HANDOVER_ACKNOWLEDGE: 0.1,
    RRC_RECONFIGURATION_COMPLETE: 0.1,
}

SATELLITE_CPU = 1
UE_CPU = 4

# The UE is actively communicating with source base station
# and the UE has not made any action
ACTIVE = "ACTIVE"
# The UE sent the measurement report and waiting for configuration
WAITING_RRC_CONFIGURATION = "WAITING_RRC_CONFIGURATION"
# The UE lost the connection without being RRC configured
# MEANING that the UE failed to be handoff.
INACTIVE = "INACTIVE"
# The UE has received the RRC configuration message
RRC_CONFIGURED = "RRC_CONFIGURED"
# The UE has sent the random access request with RRC_RECONFIGURATION_COMPLETE
WAITING_RRC_RECONFIGURATION_COMPLETE_RESPONSE = "WAITING_RRC_RECONFIGURATION_COMPLETE_RESPONSE"
