# System level config
SATELLITE_R = 25 * 1000
NUMBER_UE = 5
NUMBER_SATELLITES = 2
SATELLITE_V = 7.56 * 1000
SATELLITE_GROUND_DELAY = 30
SATELLITE_SATELLITE_DELAY = 10
DURATION = 500

# Parameters

MEASUREMENT_REPORT = "MEASUREMENT_REPORT"
HANDOVER_REQUEST = "HANDOVER_REQUEST"
HANDOVER_ACKNOWLEDGE = "HANDOVER_ACKNOWLEDGE"
RRC_RECONFIGURATION = "RRC_RECONFIGURATION"
RRC_RECONFIGURATION_COMPLETE = "RRC_RECONFIGURATION_COMPLETE"
RRC_RECONFIGURATION_COMPLETE_RESPONSE = "RRC_RECONFIGURATION_COMPLETE_RESPONSE"

PROCESSING_TIME = {
    MEASUREMENT_REPORT: 0.5,
    HANDOVER_REQUEST: 0.5,
    HANDOVER_ACKNOWLEDGE: 0.1,
    RRC_RECONFIGURATION_COMPLETE: 0.1,
}

SATELLITE_CPU = 1
UE_CPU = 4

ACTIVE = "ACTIVE"
INACTIVE = "INACTIVE"
WAITING_RRC_CONFIGURATION = "WAITING_RRC_CONFIGURATION"
WAITING_RRC_RECONFIGURATION_COMPLETE = "WAITING_RRC_RECONFIGURATION_COMPLETE"
